### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by vforv** [glaive-ai/function-calling-server#1]
Hey want to try this but getting error 
```
python3 server.py
/function-calling-server/myenv/lib/python3.10/site-packages/pydantic/_internal/_config.py:269: UserWarning: Valid config keys have changed in V2:
* 'underscore_attrs_are_private' has been removed
  warnings.warn(message, UserWarning)
Traceback (most recent call last):
  File "/home/vladimir/Documents/function-calling-server/server.py", line 41, in <module>
    model = AutoModelForCausalLM.from_pretrained(
  File "/home/vladimir/Documents/function-calling-server/myenv/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 553, in from_pretrained
    model_class = get_class_from_dynamic_module(
  File "/home/vladimir/Documents/function-calling-server/myenv/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 499, in get_class_from_dynamic_module
    return get_class_in_module(class_name, final_module.replace(".py", ""))
  File "/home/vladimir/Documents/function-calling-server/myenv/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 199, in get_class_in_module
    module = importlib.import_module(module_path)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File ".cache/huggingface/modules/transformers_modules/glaiveai/glaive-function-calling-v2-small/ee756352b27602951abdc7618c9139f1bb8e5031/modeling_mpt.py", line 18, in <module>
    from .hf_prefixlm_converter import add_bidirectional_mask_if_missing, convert_hf_causal_lm_to_prefix_lm
  File ".cache/huggingface/modules/transformers_modules/glaiveai/glaive-function-calling-v2-small/ee756352b27602951abdc7618c9139f1bb8e5031/hf_prefixlm_converter.py", line 15, in <module>
    from transformers.models.bloom.modeling_bloom import _expand_mask as _expand_mask_bloom
ImportError: cannot import name '_expand_mask' from 'transformers.models.bloom.modeling_bloom' (/home/vladimir/Documents/function-calling-server/myenv/lib/python3.10/site-packages/transformers/models/bloom/modeling_bloom.py)

```

**Comment by HAL9KKK** [comment]
transformers 4.31.0 is working

!pip install transformers==4.31.0

**Comment by perryism** [comment]
I created a PR. https://github.com/glaive-ai/function-calling-server/pull/3
